/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './abp.module';
import * as import2 from '@angular/http';
import * as import3 from './message/message.service';
import * as import4 from './log/log.service';
import * as import5 from './abpHttp';
import * as import6 from './session/abp-session.service';
import * as import7 from './auth/permission-checker.service';
import * as import8 from './features/feature-checker.service';
import * as import9 from './localization/localization.service';
import * as import10 from './settings/setting.service';
import * as import11 from './notify/notify.service';
import * as import12 from './multi-tenancy/abp-multi-tenancy.service';
import * as import13 from './abp-user-configuration.service';
import * as import14 from './auth/token.service';
import * as import15 from './utils/utils.service';
class AbpModuleInjector extends import0.ɵNgModuleInjector<import1.AbpModule> {
  _HttpModule_0:import2.HttpModule;
  _JsonpModule_1:import2.JsonpModule;
  _AbpModule_2:import1.AbpModule;
  __BrowserXhr_3:import2.BrowserXhr;
  __ResponseOptions_4:import2.BaseResponseOptions;
  __XSRFStrategy_5:any;
  __XHRBackend_6:import2.XHRBackend;
  __RequestOptions_7:import2.BaseRequestOptions;
  __MessageService_8:import3.MessageService;
  __LogService_9:import4.LogService;
  __AbpHttpConfiguration_10:import5.AbpHttpConfiguration;
  __Http_11:any;
  __ɵg_12:import2.ɵg;
  __JSONPBackend_13:import2.ɵa;
  __Jsonp_14:any;
  __AbpSessionService_15:import6.AbpSessionService;
  __PermissionCheckerService_16:import7.PermissionCheckerService;
  __FeatureCheckerService_17:import8.FeatureCheckerService;
  __LocalizationService_18:import9.LocalizationService;
  __SettingService_19:import10.SettingService;
  __NotifyService_20:import11.NotifyService;
  __AbpMultiTenancyService_21:import12.AbpMultiTenancyService;
  __AbpUserConfigurationService_22:import13.AbpUserConfigurationService;
  __TokenService_23:import14.TokenService;
  __UtilsService_24:import15.UtilsService;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _BrowserXhr_3():import2.BrowserXhr {
    if ((this.__BrowserXhr_3 == null)) { (this.__BrowserXhr_3 = new import2.BrowserXhr()); }
    return this.__BrowserXhr_3;
  }
  get _ResponseOptions_4():import2.BaseResponseOptions {
    if ((this.__ResponseOptions_4 == null)) { (this.__ResponseOptions_4 = new import2.BaseResponseOptions()); }
    return this.__ResponseOptions_4;
  }
  get _XSRFStrategy_5():any {
    if ((this.__XSRFStrategy_5 == null)) { (this.__XSRFStrategy_5 = import2.ɵb()); }
    return this.__XSRFStrategy_5;
  }
  get _XHRBackend_6():import2.XHRBackend {
    if ((this.__XHRBackend_6 == null)) { (this.__XHRBackend_6 = new import2.XHRBackend(this._BrowserXhr_3,this._ResponseOptions_4,this._XSRFStrategy_5)); }
    return this.__XHRBackend_6;
  }
  get _RequestOptions_7():import2.BaseRequestOptions {
    if ((this.__RequestOptions_7 == null)) { (this.__RequestOptions_7 = new import2.BaseRequestOptions()); }
    return this.__RequestOptions_7;
  }
  get _MessageService_8():import3.MessageService {
    if ((this.__MessageService_8 == null)) { (this.__MessageService_8 = new import3.MessageService()); }
    return this.__MessageService_8;
  }
  get _LogService_9():import4.LogService {
    if ((this.__LogService_9 == null)) { (this.__LogService_9 = new import4.LogService()); }
    return this.__LogService_9;
  }
  get _AbpHttpConfiguration_10():import5.AbpHttpConfiguration {
    if ((this.__AbpHttpConfiguration_10 == null)) { (this.__AbpHttpConfiguration_10 = new import5.AbpHttpConfiguration(this._MessageService_8,this._LogService_9)); }
    return this.__AbpHttpConfiguration_10;
  }
  get _Http_11():any {
    if ((this.__Http_11 == null)) { (this.__Http_11 = import1.abpHttpFactory(this._XHRBackend_6,this._RequestOptions_7,this._AbpHttpConfiguration_10)); }
    return this.__Http_11;
  }
  get _ɵg_12():import2.ɵg {
    if ((this.__ɵg_12 == null)) { (this.__ɵg_12 = new import2.ɵg()); }
    return this.__ɵg_12;
  }
  get _JSONPBackend_13():import2.ɵa {
    if ((this.__JSONPBackend_13 == null)) { (this.__JSONPBackend_13 = new import2.ɵa(this._ɵg_12,this._ResponseOptions_4)); }
    return this.__JSONPBackend_13;
  }
  get _Jsonp_14():any {
    if ((this.__Jsonp_14 == null)) { (this.__Jsonp_14 = import2.ɵd(this._JSONPBackend_13,this._RequestOptions_7)); }
    return this.__Jsonp_14;
  }
  get _AbpSessionService_15():import6.AbpSessionService {
    if ((this.__AbpSessionService_15 == null)) { (this.__AbpSessionService_15 = new import6.AbpSessionService()); }
    return this.__AbpSessionService_15;
  }
  get _PermissionCheckerService_16():import7.PermissionCheckerService {
    if ((this.__PermissionCheckerService_16 == null)) { (this.__PermissionCheckerService_16 = new import7.PermissionCheckerService()); }
    return this.__PermissionCheckerService_16;
  }
  get _FeatureCheckerService_17():import8.FeatureCheckerService {
    if ((this.__FeatureCheckerService_17 == null)) { (this.__FeatureCheckerService_17 = new import8.FeatureCheckerService()); }
    return this.__FeatureCheckerService_17;
  }
  get _LocalizationService_18():import9.LocalizationService {
    if ((this.__LocalizationService_18 == null)) { (this.__LocalizationService_18 = new import9.LocalizationService()); }
    return this.__LocalizationService_18;
  }
  get _SettingService_19():import10.SettingService {
    if ((this.__SettingService_19 == null)) { (this.__SettingService_19 = new import10.SettingService()); }
    return this.__SettingService_19;
  }
  get _NotifyService_20():import11.NotifyService {
    if ((this.__NotifyService_20 == null)) { (this.__NotifyService_20 = new import11.NotifyService()); }
    return this.__NotifyService_20;
  }
  get _AbpMultiTenancyService_21():import12.AbpMultiTenancyService {
    if ((this.__AbpMultiTenancyService_21 == null)) { (this.__AbpMultiTenancyService_21 = new import12.AbpMultiTenancyService()); }
    return this.__AbpMultiTenancyService_21;
  }
  get _AbpUserConfigurationService_22():import13.AbpUserConfigurationService {
    if ((this.__AbpUserConfigurationService_22 == null)) { (this.__AbpUserConfigurationService_22 = new import13.AbpUserConfigurationService(this._Http_11)); }
    return this.__AbpUserConfigurationService_22;
  }
  get _TokenService_23():import14.TokenService {
    if ((this.__TokenService_23 == null)) { (this.__TokenService_23 = new import14.TokenService()); }
    return this.__TokenService_23;
  }
  get _UtilsService_24():import15.UtilsService {
    if ((this.__UtilsService_24 == null)) { (this.__UtilsService_24 = new import15.UtilsService()); }
    return this.__UtilsService_24;
  }
  createInternal():import1.AbpModule {
    this._HttpModule_0 = new import2.HttpModule();
    this._JsonpModule_1 = new import2.JsonpModule();
    this._AbpModule_2 = new import1.AbpModule();
    return this._AbpModule_2;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.HttpModule)) { return this._HttpModule_0; }
    if ((token === import2.JsonpModule)) { return this._JsonpModule_1; }
    if ((token === import1.AbpModule)) { return this._AbpModule_2; }
    if ((token === import2.BrowserXhr)) { return this._BrowserXhr_3; }
    if ((token === import2.ResponseOptions)) { return this._ResponseOptions_4; }
    if ((token === import2.XSRFStrategy)) { return this._XSRFStrategy_5; }
    if ((token === import2.XHRBackend)) { return this._XHRBackend_6; }
    if ((token === import2.RequestOptions)) { return this._RequestOptions_7; }
    if ((token === import3.MessageService)) { return this._MessageService_8; }
    if ((token === import4.LogService)) { return this._LogService_9; }
    if ((token === import5.AbpHttpConfiguration)) { return this._AbpHttpConfiguration_10; }
    if ((token === import2.Http)) { return this._Http_11; }
    if ((token === import2.ɵg)) { return this._ɵg_12; }
    if ((token === import2.JSONPBackend)) { return this._JSONPBackend_13; }
    if ((token === import2.Jsonp)) { return this._Jsonp_14; }
    if ((token === import6.AbpSessionService)) { return this._AbpSessionService_15; }
    if ((token === import7.PermissionCheckerService)) { return this._PermissionCheckerService_16; }
    if ((token === import8.FeatureCheckerService)) { return this._FeatureCheckerService_17; }
    if ((token === import9.LocalizationService)) { return this._LocalizationService_18; }
    if ((token === import10.SettingService)) { return this._SettingService_19; }
    if ((token === import11.NotifyService)) { return this._NotifyService_20; }
    if ((token === import12.AbpMultiTenancyService)) { return this._AbpMultiTenancyService_21; }
    if ((token === import13.AbpUserConfigurationService)) { return this._AbpUserConfigurationService_22; }
    if ((token === import14.TokenService)) { return this._TokenService_23; }
    if ((token === import15.UtilsService)) { return this._UtilsService_24; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const AbpModuleNgFactory:import0.NgModuleFactory<import1.AbpModule> = new import0.NgModuleFactory<any>(AbpModuleInjector,import1.AbpModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovUmVwb3NpdG9yaWVzL0dpdGh1Yi9hYnAtbmcyLW1vZHVsZS9zcmMvYWJwLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9SZXBvc2l0b3JpZXMvR2l0aHViL2FicC1uZzItbW9kdWxlL3NyYy9hYnAubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
